openapi: 3.0.0
info:
  title: Orders API
  version: "1.0"
  description: API для работы с заказами (поиск, получение).
servers:
  - url: http://localhost:8080/api/v1
paths:
  /orders:
    get:
      summary: Получение списка ID заказов
      description: Возвращает список ID заказов с пагинацией и поиском
      tags:
        - orders
      parameters:
        - in: query
          name: search
          schema:
            type: string
          required: false
          description: Поиск по UID заказа
        - in: query
          name: page
          schema:
            type: integer
            minimum: 0
            default: 0
          required: false
          description: Номер страницы
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
          required: false
          description: Размер страницы
      responses:
        "200":
          description: Список ID заказов
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders_ids:
                    type: array
                    items:
                      type: string
                  total_orders:
                    type: integer
        "400":
          description: Неверные параметры
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Внутренняя ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /orders/{order_id}:
    get:
      summary: Получение заказа
      description: Возвращает подробную информацию о заказе по его ID
      tags:
        - orders
      parameters:
        - in: path
          name: order_id
          schema:
            type: string
          required: true
          description: UID заказа
      responses:
        "200":
          description: Заказ найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  order:
                    $ref: "#/components/schemas/OrderDto"
        "404":
          description: Заказ не найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Внутренняя ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    OrderDto:
      type: object
      properties:
        order_uid:
          type: string
        track_number:
          type: string
        entry:
          type: string
        delivery_service:
          type: string
        date_created:
          type: string
          format: date-time
        delivery:
          $ref: "#/components/schemas/DeliveryDto"
        payment:
          $ref: "#/components/schemas/PaymentDto"
        items:
          type: array
          items:
            $ref: "#/components/schemas/ItemDto"

    DeliveryDto:
      type: object
      properties:
        name:
          type: string
        zip:
          type: string
        city:
          type: string
        address:
          type: string
        region:
          type: string

    PaymentDto:
      type: object
      properties:
        currency:
          type: string
        provider:
          type: string
        amount:
          type: integer
        payment_dt:
          type: integer
        bank:
          type: string
        delivery_cost:
          type: number
        goods_total:
          type: integer
        custom_fee:
          type: number

    ItemDto:
      type: object
      properties:
        track_number:
          type: string
        price:
          type: number
        name:
          type: string
        sale:
          type: number
          format: float
        size:
          type: string
        total_price:
          type: number
        brand:
          type: string
